---
layout:     post
title:      CompletableFuture 对象一致性问题
subtitle:   CompletableFuture 对象一致性问题
categories: [gpt]
mermaid: false
sequence: false
flow: false
mathjax: false
mindmap: false
mindmap2: false
---

# 1. 问题如下
```java
我写了一个案例，关于CompletableFuture的，如下是我的案例：package test;

import java.util.concurrent.*;


public class MyCompletableFuture {

    private static ThreadPoolExecutor taskPool = new ThreadPoolExecutor(30, 50, 0, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>(300), new ThreadPoolExecutor.CallerRunsPolicy());
    private static ThreadPoolExecutor monitorPool = new ThreadPoolExecutor(30, 50, 0, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>(300), new ThreadPoolExecutor.CallerRunsPolicy());

    public static void main(String[] args) {

        for (int i = 0; i < 1000; i++) {
            MyMessageInfo myMessageInfo = new MyMessageInfo();
            myMessageInfo.setName(String.valueOf(i));
            CompletableFuture.supplyAsync(() -> runTask(myMessageInfo), taskPool).orTimeout(5, TimeUnit.SECONDS).exceptionallyAsync(e -> {
                if (e instanceof TimeoutException) {
                    // 处理5s超时，执行降级流程
                    System.out.println(Thread.currentThread().getName() + "run,name is :" + myMessageInfo.getName());
                }
                return null;
            }, monitorPool);
        }

    }


    public static String runTask(MyMessageInfo info) {
        if ("10".equals(info.getName()) || "100".equals(info.getName()) || "500".equals(info.getName())) {
            try {
                Thread.sleep(300000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println(Thread.currentThread().getName() + "run,name is :" + info.getName());
        return info.getName();
    }
}关于这个案例，我想详细的了解，在使用CompletableFuture的各种组合中，因为里面涉及各种线程池去异步执行任务，这个任务的载体就是MyMessageInfo 对象，我想进一步了解，从使用CompletableFuture开始，这个对象在后续的执行过程中，是否能够保证每一个CompletableFuture操作的就是同一个MyMessageInfo 对象呢？因为后续的流程涉及到在异步线程池中执行这个任务，监听这个任务超时，超时后又在另外一个线程池中执行这个超时的对象，我害怕这个对象在整个流程中最后发生变化，也就是一个CompletableFuture流程中如何确保超时时执行的那个任务就是任务线程池中确实超时的那个任务呢？而不是第二次提交进来的任务对象
```
在使用 `CompletableFuture` 的时候，你提到的关键问题是确保在异步执行任务时，`MyMessageInfo` 对象的一致性问题，以及超时处理流程中是否会混淆不同的任务对象。为了回答你的问题，首先需要理解以下几点：

### 1. **CompletableFuture 的异步执行原理**
   
   `CompletableFuture.supplyAsync` 是一个异步任务启动方法，默认使用一个 `ForkJoinPool` 来执行异步任务，或者你可以通过传递自定义的线程池（如你的 `taskPool`）来管理异步任务的执行。

   当你调用 `CompletableFuture.supplyAsync(() -> runTask(myMessageInfo), taskPool)`，会立即返回一个 `CompletableFuture` 对象，而任务 `runTask(myMessageInfo)` 会异步提交到 `taskPool` 中执行。因为每个异步任务接收到的 `myMessageInfo` 是通过你创建的循环生成的独立对象（每次都是新的实例），所以每个任务都拥有它自己的 `MyMessageInfo` 实例，任务执行时，该对象不会被其他任务覆盖。

### 2. **CompletableFuture 的异常处理和超时处理**

   接下来你在每个 `CompletableFuture` 上注册了 `.orTimeout(5, TimeUnit.SECONDS)`，用于处理任务超时。这里设置了一个超时时间，表示如果任务在 5 秒内没有完成，则会抛出 `TimeoutException`。随后你使用了 `.exceptionallyAsync(e -> {...}, monitorPool)` 来在另一个线程池中处理这个超时异常。

   在 `exceptionallyAsync` 中，你确实可以捕获到异常，并且你对异常进行了类型判断，以确定是否是 `TimeoutException`。这部分逻辑也运行在你传递的 `monitorPool` 中。

### 3. **线程池中的对象引用**

   由于 `CompletableFuture` 的所有操作链（包括 `.orTimeout` 和 `.exceptionallyAsync`）都是基于同一个 `CompletableFuture` 实例，且每个 `CompletableFuture` 都是对同一个 `myMessageInfo` 的引用，因此你可以放心地认为，处理超时的 `exceptionallyAsync` 操作链中所使用的 `myMessageInfo` 对象仍然是提交任务时传入的那个对象。这是因为 Java 的对象引用机制：即使任务在不同的线程中执行，所有的操作链都共享的是同一个 `myMessageInfo` 对象的引用，而不是复制对象本身。

### 4. **任务对象一致性保证**
   
   你担心的情况是，假如某个任务超时，`exceptionallyAsync` 处理的是不是确实超时的那个任务，而不是后来提交的任务。

   可以肯定地说，在 `CompletableFuture` 的生命周期中，所有的操作（如 `supplyAsync`、`orTimeout`、`exceptionallyAsync`）都只会操作最初提交任务时的 `MyMessageInfo` 对象。因此，无论任务是否超时，超时处理函数中处理的对象依然是与最初异步任务绑定的那个 `MyMessageInfo`，不会被覆盖或混淆。Java 中的对象引用使得这个对象的一致性得到了保证。

   **总结：** 
   - 每次 `CompletableFuture.supplyAsync()` 传递的是不同的 `MyMessageInfo` 实例，因此每个异步任务处理的都是它自己的对象。
   - 在任务超时后处理超时的 `exceptionallyAsync` 中，使用的 `MyMessageInfo` 对象仍然是原始任务中传入的对象，不会因为有其他新的任务提交而发生变化或被覆盖。
   - Java 的对象引用机制确保了对象的一致性，多个线程处理的是同一个对象的引用。

你可以通过打印对象的 `hashCode` 来验证，在整个任务执行链中，`MyMessageInfo` 的引用始终是相同的。

# 2. 其实我之前也有链式编程的经验，以及链式编程中传递函数式接口（比如传入一个Lambda表达式，类似Function的实例或者Runnable的实例），而且我也知道传入一个Lambda表单式其本质式传入了一个匿名内部类对象实例，只是在CompletableFuture这种链式编程中，反复的传入一个任务表达式，我就不太清楚这个任务表达式的底层到底是如何实现的？你是否可以从匿名内部类对象那种最底层的实现上帮我刨析CompletableFuture这种链式编程中，这个任务对象到底是以什么方式存在的。当然，我知道在它编译后的实现中并不是对应的匿名内部类对象，只是我想从最传统的方式来理解CompletableFuture的这种行为。
你的问题涉及到从底层实现的角度，来理解 `CompletableFuture` 链式编程中的任务对象是如何存在和传递的。虽然现代 Java 使用 `Lambda` 表达式简化了代码书写，但从实现的角度看，Lambda 表达式背后实际上还是匿名类的一种优化和简化。让我们从传统的匿名内部类出发，深入了解 `CompletableFuture` 是如何处理这些任务表达式的。

### 1. **Lambda 表达式和匿名内部类的关系**

在 Java 中，`Lambda` 表达式的本质是一个**函数式接口**的实现。函数式接口就是只有一个抽象方法的接口，比如 `Runnable`、`Callable`、`Function`、`Consumer` 等。Java 使用 `Lambda` 表达式来简化代码，并在编译时生成与匿名内部类类似的字节码。

例如，下面这段 `Lambda` 代码：

```java
Runnable r = () -> System.out.println("Hello, world!");
```

编译后本质上相当于：

```java
Runnable r = new Runnable() {
    @Override
    public void run() {
        System.out.println("Hello, world!");
    }
};
```

在编译时，`Lambda` 实际上生成了一个**静态方法**，并且通过 `invokedynamic` 指令在运行时动态地将其绑定到函数式接口。与匿名内部类不同，`Lambda` 并不显式创建类文件，而是通过字节码动态生成，因此它比传统的匿名内部类更轻量、高效。

### 2. **在 CompletableFuture 中的 Lambda 表达式传递**

在 `CompletableFuture` 的链式编程中，你多次传递任务表达式（例如 `supplyAsync` 和 `exceptionallyAsync` 中的 Lambda 表达式）。这些 Lambda 表达式会被编译成实现了 `Function` 或 `Supplier` 接口的实例，并且在 `CompletableFuture` 内部是通过以下方式进行处理的：

- `CompletableFuture.supplyAsync()` 需要一个 `Supplier<T>` 函数式接口的实现，该接口定义了一个 `get()` 方法。你传递的 `Lambda` 表达式会被编译成一个 `Supplier<T>` 的匿名实现类，类似于：

    ```java
    Supplier<String> supplier = new Supplier<String>() {
        @Override
        public String get() {
            return runTask(myMessageInfo);
        }
    };
    ```

- `CompletableFuture.exceptionallyAsync()` 需要一个 `Function<Throwable, T>`，用于处理异常。你传递的 Lambda 表达式会被编译成类似的 `Function` 实现：

    ```java
    Function<Throwable, String> exceptionallyFunction = new Function<Throwable, String>() {
        @Override
        public String apply(Throwable e) {
            if (e instanceof TimeoutException) {
                System.out.println("Handling TimeoutException");
            }
            return null;
        }
    };
    ```

### 3. **CompletableFuture 内部如何管理任务**

`CompletableFuture` 通过维护内部的**执行链**，将这些任务表达式（即 `Lambda` 表达式或匿名内部类的实例）依次存储和管理。每次你调用链式方法，比如 `thenApply()` 或 `exceptionallyAsync()`，都会将传入的任务函数存储在一个内部的数据结构中。

- `CompletableFuture` 中有一个内部类 `UniCompletion`，它代表每个阶段的任务。每个 `Lambda` 表达式会被封装成 `UniCompletion` 实例，作为执行链的一部分。

- 当一个任务完成时，`CompletableFuture` 会依次触发这些 `UniCompletion` 实例，从而保证任务链的有序执行。

### 4. **Lambda 表达式的底层执行**

编译后的 `Lambda` 表达式不会生成额外的类文件，而是通过 `invokedynamic` 指令动态生成方法句柄，并将其绑定到运行时的函数式接口。可以将其理解为编译时生成的**方法引用**，这些引用在运行时被动态调用。如下是一个简单的步骤描述：

1. 当你使用 `CompletableFuture.supplyAsync()` 传递一个 `Lambda` 表达式时，Java 会生成一个对应的静态方法，并通过 `invokedynamic` 指令来动态创建一个 `Supplier` 实例。
2. 这个 `Supplier` 实例作为任务被提交到 `ThreadPoolExecutor` 中的某个线程执行。
3. 当任务执行完毕，`CompletableFuture` 会检查是否有后续的链式操作（比如 `.thenApply()`），如果有则继续执行下一个 `Lambda`（同样以函数式接口的形式存储）。

### 5. **CompletableFuture 中的任务对象如何保持一致性**

在 `CompletableFuture` 链式操作中，每次传递的 `Lambda` 表达式操作的对象都是相同的**引用**。例如，你传入的 `myMessageInfo` 对象会以引用的方式传递给 `Lambda` 表达式，而不是值传递。即使 Lambda 表达式在不同的线程中执行，它操作的仍然是同一个对象的引用，因此不会出现任务对象不一致的问题。

### 总结

- `CompletableFuture` 中的 `Lambda` 表达式最终会编译成实现了相应函数式接口（如 `Supplier` 或 `Function`）的匿名类实例。`Lambda` 只是一种简化代码的语法糖，其本质上仍是基于匿名类的实现。
- 在 `CompletableFuture` 内部，每个 `Lambda` 表达式会被包装成一个内部的任务单元，并通过 `invokedynamic` 指令动态绑定到接口实现。
- 在整个执行链中，任务对象（如 `myMessageInfo`）是通过引用传递的，确保了在任务执行和异常处理时对象的一致性。

通过这种方式，你可以从传统的匿名内部类角度来理解 `CompletableFuture` 的行为。每一个 `Lambda` 实际上对应的是一个匿名内部类的实例，只不过编译器和虚拟机对其做了性能优化。

# 3. 代码如下
```java
package com.riskcontrol.cron.support;

import com.riskcontrol.common.enums.RiskFilterSourceEnum;
import com.riskcontrol.common.enums.RiskFilterStatusEnum;
import com.riskcontrol.common.enums.RiskFilterTypeEnum;
import com.riskcontrol.common.enums.RuleEnum;
import com.riskcontrol.common.exception.BusinessException;
import com.riskcontrol.common.utils.LogUtils;
import com.riskcontrol.cron.constants.ProjectConstant;
import com.riskcontrol.cron.engine.OriWithdrawReq;
import com.riskcontrol.cron.engine.WithdrawContext;
import com.riskcontrol.cron.entity.RiskFilterLog;
import com.riskcontrol.cron.service.WithdrawService;
import com.riskcontrol.cron.utils.ProductConstantsLoader;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import static com.riskcontrol.cron.enums.WithdrawFilterEnum.CURRENT_ENTER_MANUALLY;
import static com.riskcontrol.cron.enums.WithdrawFilterEnum.NEXT_ENTER_MANUALLY;

@Component
@Slf4j
public class WithdrawServiceDelegate {

    @Resource(name = "withdrawExecutorService")
    private ExecutorService executorService;

    @Resource(name = "withdrawExecutorTimeOutService")
    private ExecutorService executorTimeOutService;

    @Resource
    private WithdrawService withdrawService;

    /**
     * 处理取款消息
     *
     * @param req
     */
    public void handleWithdraw(OriWithdrawReq req) {
        log.info("进入熔断流程处理，正常流程和熔断流程异步进行");
        // 设置风控日志记录器
        req.setRiskFilterLogger(withdrawService::handleRiskLog);
        int out = obtainTimeOut();
        Map<String, String> mdcContextMap = LogUtils.getMDCContextMap();
        CompletableFuture.supplyAsync(() -> needManual(req), executorService).thenCompose(needManual -> {
            if (Objects.isNull(needManual)) {
                log.info("[双流程]当前消息 requestId {} 非法，消息丢弃", req.getRequestId());
                return null;
            }
            if (needManual) {
                // 转人工处理
                return CompletableFuture.supplyAsync(() -> {
                    log.info("[双流程]当前消息 requestId {} 上一笔请求状态为-4，直接进入人工处理", req.getRequestId());
                    LogUtils.setMDCContextMap(mdcContextMap);
                    return withdrawService.modifyExceptionPrompt(withdrawService.weaveLogicForWithdrawContext(new WithdrawContext(), c -> {
                        c.setReq(req);
                        c.setAutoApprove(false);
                        c.setExceptionPromptType(CURRENT_ENTER_MANUALLY.getType());
                        c.setExceptionPrompt(CURRENT_ENTER_MANUALLY.getFilterMsg());
                        return c;
                    }));
                }, executorService);
            } else {
                return CompletableFuture.supplyAsync(() -> {
                    log.info("[双流程][正常流程]当前消息 requestId {} 进入正常处理流程", req.getRequestId());
                    LogUtils.setMDCContextMap(mdcContextMap);
                    // 无论是否超时，都执行正常流程
                    return withdrawService.withdrawRisk(req, true, false);
                }, executorService).orTimeout(out, TimeUnit.SECONDS).exceptionallyAsync(e -> {
                    if (e instanceof TimeoutException) {
                        // 处理5s超时，超时后同时执行降级流程
                        log.info("[双流程][熔断流程]当前消息 requestId {} 进入超时熔断处理流程", req.getRequestId());
                        LogUtils.setMDCContextMap(mdcContextMap);
                        return withdrawService.withdrawRiskWithDowngrade(req);
                    }
                    return false;
                }, executorTimeOutService);
            }
        }).exceptionally(e -> {
            if (req.isNeedLogger() && Objects.nonNull(req.getRiskFilterLogger())) {
                String message;
                if (e instanceof BusinessException) {
                    message = Objects.nonNull(e.getCause()) ? e.getCause().getMessage() : e.getMessage();
                } else {
                    message = e.getMessage();
                }
                RiskFilterLog riskFilterLog = new RiskFilterLog();
                riskFilterLog.setFilterType(RiskFilterTypeEnum.WITHDRAW_RISK.getCode());
                riskFilterLog.setStatus(RiskFilterStatusEnum.INITIAL.getCode());
                riskFilterLog.setSource(RiskFilterSourceEnum.WITHDRAW_RISK.getCode());
                riskFilterLog.setRequestId(req.getRequestId());
                riskFilterLog.setRiskRuleAction(RuleEnum.TRANSFERRED_TO_MANUAL_REVIEW.getRuleAction());
                riskFilterLog.setErrorMsg(StringUtils.substring(message, 0, 255));
                req.getRiskFilterLogger().accept(true, true, req.getRequestId(), riskFilterLog);
            }
            return false;
        });
    }

    /**
     * 获取任务执行超时时间
     *
     * @return
     */
    private int obtainTimeOut() {
        int out = 5;
        try {
            String timeOut = ProductConstantsLoader.obtainProductConstantRedis(ProjectConstant.PRODUCT_CONSTANTS_C66, ProjectConstant.PRODUCT_CONSTANTS_TYPE_0014, ProjectConstant.JMS_WITHDRAW_RISK_LISTENER_TIMEOUT);
            out = Integer.valueOf(timeOut);
        } catch (Exception e) {
            log.error("JMS_WITHDRAW_RISK_LISTENER_TIMEOUT 配置无效，取默认值5秒钟");
        }
        log.info("[双流程]任务超时时间设置为{}秒钟", out);
        return out;
    }

    /**
     * 当前订单是否需要转人工
     *
     * @param req 当前订单信息
     * @return 是否需要转人工 true：需要 false：不需要 null：无效消息
     */
    private Boolean needManual(OriWithdrawReq req) {
        return Optional.ofNullable(withdrawService.queryLastOrder(req)).map(e -> NEXT_ENTER_MANUALLY.getType().equals(e.getExceptionPromptType())).orElse(null);
    }

}在这段流程中，我使用了CompletableFuture执行一个异步任务，后续还使用了thenCompose，在thenCompose里面又开启了新的CompletableFuture执行异步任务，请问我在最外层最后exceptionally中记录了日志，这里捕获到的异常是流程中任何节点抛出的异常么？
```
是的，在你提供的代码中，`CompletableFuture` 通过链式调用来处理任务。在 `exceptionally` 中捕获的异常，实际上是整个 `CompletableFuture` 链中任何节点抛出的异常。这意味着在 `thenCompose` 及其后的所有异步任务执行过程中，如果发生了异常，这些异常都会传递到 `exceptionally`。

### 具体流程解析：

1. **异步任务启动 (`supplyAsync`)**：
   你使用了 `CompletableFuture.supplyAsync()` 方法，这会开启一个新的异步任务来执行 `needManual(req)`。这个异步任务返回一个 `CompletableFuture<Boolean>` 对象。

2. **`thenCompose`**：
   当上一个 `CompletableFuture` 任务完成后，`thenCompose` 会根据结果 (`needManual`) 执行不同的逻辑，可能会再次启动新的 `CompletableFuture` 异步任务。这个流程中，无论是处理人工操作（`withdrawService.modifyExceptionPrompt`），还是正常的风险处理流程（`withdrawService.withdrawRisk`），以及后续的超时异常处理，都使用了异步操作。

3. **异常捕获 (`exceptionally`)**：
   `exceptionally` 方法会捕获整个 `CompletableFuture` 链中抛出的异常，包括：
   - 初始任务 `needManual(req)` 的异常
   - `thenCompose` 中所有后续任务的异常（包括人工处理逻辑、正常流程处理逻辑和熔断处理逻辑中的任何异常）
   - 如果 `orTimeout` 设置的超时条件触发，也会抛出 `TimeoutException`，并在超时处理逻辑中执行额外的操作。超时属于一种特殊的异常，也可以被 `exceptionally` 捕获。

### 异常传播机制：
- **任务中抛出的异常**会沿着 `CompletableFuture` 链向下传播。即使你在某个任务中抛出了异常，它不会立即终止整个链，而是等待是否有捕获异常的机制（如 `exceptionally`）。
- **如果链中任何一个任务抛出异常**，这个异常将被传递给后续的异常处理节点，在你的代码中，`exceptionally` 是最终的异常捕获节点。

### 结论：
- 在你这个 `CompletableFuture` 链式调用中，`exceptionally` 中捕获的异常确实是来自任何链中节点的异常。
- 无论是 `supplyAsync`、`thenCompose` 中的任务，还是 `orTimeout` 中的超时异常，一旦出现异常，它们都会被捕获，并传递给 `exceptionally` 进行处理。在 `exceptionally` 中你记录日志，并执行相应的错误处理逻辑。

# 4. 请原谅我对这个东西理解上的困难。我们知道，在原始的异步线程中，抛出的异常默认外部线程是没法感知和捕获的，我不知道completableFuture底层到底做了什么实现。从你的回答中，我似乎感觉到它只要确保最外层提交的是向一个completableFuture中提交一个任务，然后似乎就不用关注这个future里面是如何复杂，哪怕是开启了多个异步链路，只要确保始终操作的是同一个future，它底层就能确保始终操作的就是这个任务，哪怕这个任务被反复提交给其他内部的completabkeFuture去异步处理，最终这个链路上都能始终保证异常，以及任务的一致性？请注意，我里面又重启了一个completabkeFuture去执行超时任务并且处理了异常，那这个异常还会继续抛出来给最外层的future吗？这种处理机制让我感到十分不解。
你提出的困惑非常合理，`CompletableFuture` 的确提供了一种特殊的机制来处理异步操作的异常传播和任务的结果跟踪。为了解释清楚 `CompletableFuture` 如何确保在复杂的异步链路中保证任务的一致性和异常的捕获，我们需要深入了解其底层的工作原理。

### 问题总结：
你的问题可以分为几个核心点：
1. **原始线程中的异常处理**：传统的异步线程中，抛出的异常是无法直接被外部捕获的，只有通过显式的 `try-catch` 或者 `Future.get()` 才能捕获。
2. **`CompletableFuture` 的异常传播机制**：为什么 `CompletableFuture` 能捕获异步链路中的所有异常，无论这个链条有多复杂？
3. **任务的一致性**：无论多少 `CompletableFuture` 在链式调用中相互依赖，最终外层的 `CompletableFuture` 都能够保证异常传播和任务结果的一致性。

我们先从 `CompletableFuture` 的底层设计出发，再通过代码的行为解析来解答你的问题。

### 1. `CompletableFuture` 的底层机制

`CompletableFuture` 是 Java 8 引入的一种异步编程工具，它本质上是对任务的一个 **包装**，可以理解为它将任务分解成一系列的步骤，并且保证每个步骤的执行情况（成功或失败）可以被下一个步骤感知和处理。这种设计就是所谓的 **“链式回调”**。

- 每个 `CompletableFuture` 都包含了任务执行的 **结果状态**，这个结果状态可以是 **正常结果**，也可以是 **异常**。
- `CompletableFuture` 底层使用的是 **回调机制**，它会在任务完成（无论是成功还是失败）时通知接下来的任务继续执行。
- `CompletableFuture` 的链条操作确保了 **任务依赖的顺序**。例如 `thenCompose` 会在上一个任务完成后才启动下一个任务，而 `exceptionally` 会在发生异常时触发异常处理逻辑。

### 2. 异常传播机制

在传统的 `Future` 中，异常必须通过 `Future.get()` 来显式捕获，异步任务执行时的异常如果没有被捕获，是不会被外部线程知道的。而 `CompletableFuture` 解决了这个问题，保证了异常能够在链式操作中自动传播。

#### 异常传播如何工作？

- 当你使用 `CompletableFuture.supplyAsync()` 启动任务时，它返回一个 `CompletableFuture`，这个对象实际上维护了一个任务的结果状态（可以是成功，也可以是异常）。
- 当任务抛出异常时，`CompletableFuture` 会将该异常 **封装到它的状态中**，并且这个异常会在后续的链式调用中 **自动传播**。
- 这种设计使得在任何链路中的异常，都会最终被链条中的下一个 `exceptionally` 或者 `handle` 处理。

#### 关于你的代码：

在你的代码中，你有一个超时处理任务，它通过 `orTimeout()` 方法定义了一个超时异常逻辑。这个方法会将 `TimeoutException` 抛出，同时该异常会 **沿着链条传递**，直到遇到异常处理节点（例如 `exceptionally`）。

```java
return CompletableFuture.supplyAsync(() -> {
    // 正常流程逻辑
}, executorService).orTimeout(out, TimeUnit.SECONDS).exceptionallyAsync(e -> {
    // 超时或其他异常处理逻辑
}, executorTimeOutService);
```

这里的异常处理设计是 **嵌套的**，也就是说，任何任务中抛出的异常都会被传递给外层的 `CompletableFuture`，并最终被 `exceptionally` 捕获。

### 3. 任务一致性

`CompletableFuture` 能够确保任务一致性的核心机制是 **状态的单一性**。即便多个任务在链条中被处理，所有操作的最终结果都会汇聚到 **最外层的 `CompletableFuture`** 上。它通过以下几点保证了这一点：

- **单一结果模型**：每个 `CompletableFuture` 只会有 **一个最终结果**，要么是正常的结果，要么是异常。这一点类似于状态机，任务状态只能从 "未完成" 变为 "已完成"（无论成功或失败）。
- **状态传播**：当一个任务完成（无论成功或失败）后，这个状态会 **传播** 到后续的任务，而后续任务的状态会继续传播。通过链式操作，`CompletableFuture` 保证了任务结果的一致性和传播性。

### 代码中的具体处理

你在 `thenCompose` 中又启动了新的 `CompletableFuture`，这实际上是通过嵌套的 `CompletableFuture` 实现复杂的异步流程。尽管看起来每个任务是独立的，但是它们实际上共享同一个任务结果状态。当一个任务抛出异常，`CompletableFuture` 底层会将这个异常捕获并继续传递给后续任务链。

在你代码中的 `orTimeout` 的部分，其实超时任务中的异常也会自动传播到外层，因为 **`exceptionally` 是捕获所有异常的最后一层处理器**。

```java
return CompletableFuture.supplyAsync(() -> {
    // 正常流程逻辑
}, executorService).orTimeout(out, TimeUnit.SECONDS).exceptionallyAsync(e -> {
    // 超时或其他异常处理逻辑
    if (e instanceof TimeoutException) {
        // 处理超时
    }
    return false;
}, executorTimeOutService);
```

无论是正常的任务还是异常抛出（如超时），都能被最终的 `exceptionally` 捕获，并统一处理。

### 结论

- `CompletableFuture` 通过链式操作 **自动传播异常**，确保在异步任务链中的任何异常都能被最终捕获。
- 异步链中任何任务的状态（成功或失败）都会被传递到最终的 `CompletableFuture`，这保证了任务结果的一致性。
- 你在超时逻辑中处理的异常也会被外层捕获，因为 `exceptionally` 是整个链路的异常终结者。

因此，虽然你在链条中多次启动了异步任务，但只要这些任务都是通过 `CompletableFuture` 连接的，异常传播和任务结果都会自动传播到最外层的 `CompletableFuture`，无需额外的异常捕获逻辑。

# 5. 那如果在执行超时逻辑中，超时逻辑也抛出了异常，这个异常如何传播呢？
在 `CompletableFuture` 中，如果执行 **超时逻辑** 的过程中再次抛出了异常，该异常仍然会被 **进一步传播**，并且遵循相同的异常处理链条规则。无论是执行任务本身的异常，还是在处理超时逻辑时的异常，`CompletableFuture` 都会将异常捕获并传递给下一个能够处理异常的节点（如 `exceptionally` 或 `handle`）。

### 异常传播的具体机制

`CompletableFuture` 的异常传播机制遵循以下原则：
1. **任务执行中的异常**：当异步任务执行过程中抛出异常时，`CompletableFuture` 将该异常存储在它的内部状态中，等待后续的异常处理逻辑来处理它。
   
2. **超时逻辑中的异常**：如果在超时逻辑的 `exceptionallyAsync` 或 `handleAsync` 中再次抛出了异常，`CompletableFuture` 同样会捕获这个异常并将其传递给后续的异常处理节点。

3. **最终异常捕获点**：通常在链式调用中，`exceptionally` 或 `handle` 是最后一个捕获异常的节点。如果某个节点没有处理异常，异常将继续向下传递，直到被某个节点处理或在没有异常处理器的情况下，传播到最外层。

### 举个例子

假设你有以下代码，其中在处理超时逻辑时再次抛出了异常：

```java
CompletableFuture.supplyAsync(() -> {
    // 执行异步任务
    return "正常结果";
}, executorService)
.orTimeout(1, TimeUnit.SECONDS)
.exceptionallyAsync(e -> {
    // 处理超时或其他异常
    if (e instanceof TimeoutException) {
        System.out.println("超时异常处理");
        throw new RuntimeException("处理超时时的异常");
    }
    return "默认值";
}, executorTimeOutService)
.exceptionally(e -> {
    // 捕获上一个处理器中的异常
    System.out.println("最终捕获的异常: " + e.getMessage());
    return "任务失败";
});
```

### 分析

1. **正常任务执行**：假设异步任务没有问题，正常完成则不会进入超时逻辑。
2. **超时发生**：如果超时发生，`orTimeout` 会抛出 `TimeoutException`，并进入 `exceptionallyAsync` 来处理该异常。
3. **超时逻辑中的异常**：在 `exceptionallyAsync` 处理超时异常时，假设你再次抛出了 `RuntimeException("处理超时时的异常")`，此时这个新的异常会被 `CompletableFuture` 捕获并传递给下一个 `exceptionally`。
4. **最终异常捕获**：下一个 `exceptionally` 捕获到了这个新的 `RuntimeException`，并处理该异常，输出 "最终捕获的异常: 处理超时时的异常"，然后返回 `"任务失败"` 作为最终的结果。

### 重要提示

- **每一个链条上的异常都可以继续传播**：即使在异常处理逻辑中再次抛出异常，`CompletableFuture` 会继续向下传递该异常，直到有合适的处理器进行处理。如果没有处理器处理这个异常，那么会抛出 `CompletionException`，它将封装你最后抛出的异常。
  
- **异常封装在 `CompletionException` 中**：所有 `CompletableFuture` 的异常最终会被封装在 `CompletionException` 中，如果你直接在代码的外层调用 `get()` 方法，那么你需要注意捕获这个 `CompletionException` 来处理异步任务中的异常。

### 代码结果

在上面这个例子中，程序的输出将是：

```
超时异常处理
最终捕获的异常: 处理超时时的异常
```

最终的 `CompletableFuture` 返回结果为 `"任务失败"`。

### 结论

1. **异常在链路中自动传播**：即使在异常处理过程中再次抛出异常，`CompletableFuture` 仍然会将这个异常传递给下一个异常处理器，直到最终被处理。
2. **灵活的异常处理**：你可以在链条的任何位置使用 `exceptionally` 或 `handle` 来处理异常，也可以在处理器中再次抛出新的异常，这些异常都将被捕获并继续传播。

# 6. 我觉得我的代码有问题，我在内部的超时异常处理中只判断了当异常类型是timeoutException时才启动一个新的异步流程，那对于不是这个类型的异常我直接返回了false，这里我是不是应该把其他异常在内部直接手动抛出去才能被最外层的exceptionkky捕获到呢？因为最外层的异常目的是为了记录日志。
是的，你的判断和处理方式确实存在问题。

在当前代码中，你只处理了 `TimeoutException` 的情况，并直接返回了 `false`。这样做的确会导致非 `TimeoutException` 的异常不会被最外层的 `exceptionally` 捕获，而是被直接返回了 `false`，从而掩盖了其他可能的重要异常。

### 改进建议

为了确保所有异常都能够被捕获并记录日志，你应该对非 `TimeoutException` 的异常进行重新抛出，而不是简单地返回 `false`。这样可以确保这些异常能够在最外层的 `exceptionally` 中被捕获到。

### 修改后的代码：

```java
CompletableFuture.supplyAsync(() -> {
    log.info("[双流程][正常流程]当前消息 requestId {} 进入正常处理流程", req.getRequestId());
    LogUtils.setMDCContextMap(mdcContextMap);
    return withdrawService.withdrawRisk(req, true, false);
}, executorService)
.orTimeout(out, TimeUnit.SECONDS)
.exceptionallyAsync(e -> {
    if (e instanceof TimeoutException) {
        // 处理超时异常并启动熔断处理
        log.info("[双流程][熔断流程]当前消息 requestId {} 进入超时熔断处理流程", req.getRequestId());
        LogUtils.setMDCContextMap(mdcContextMap);
        return withdrawService.withdrawRiskWithDowngrade(req);
    } else {
        // 如果不是 TimeoutException，重新抛出异常以便最外层处理
        log.error("[双流程] 异常处理过程中发生非超时异常: {}", e.getMessage(), e);
        throw new RuntimeException(e);
    }
}, executorTimeOutService);
```

### 改进要点：

1. **捕获并重新抛出非 `TimeoutException` 的异常**：当异常不是 `TimeoutException` 时，你不应该直接返回 `false`，而是应该将这个异常重新抛出，这样它才能被 `CompletableFuture` 继续传播到最外层的 `exceptionally` 处理。

2. **最外层 `exceptionally` 捕获所有异常并记录日志**：
   这样确保了任何在异步链路中的异常（无论是在超时逻辑中，还是在其他异步任务中发生的异常）都会最终到达最外层的 `exceptionally`，并能够被捕获、记录日志。

### 完整流程示例：

```java
CompletableFuture.supplyAsync(() -> {
    log.info("[双流程][正常流程]当前消息 requestId {} 进入正常处理流程", req.getRequestId());
    LogUtils.setMDCContextMap(mdcContextMap);
    return withdrawService.withdrawRisk(req, true, false);
}, executorService)
.orTimeout(out, TimeUnit.SECONDS)
.exceptionallyAsync(e -> {
    if (e instanceof TimeoutException) {
        log.info("[双流程][熔断流程]当前消息 requestId {} 进入超时熔断处理流程", req.getRequestId());
        LogUtils.setMDCContextMap(mdcContextMap);
        return withdrawService.withdrawRiskWithDowngrade(req);
    } else {
        // 重新抛出非超时异常
        log.error("[双流程] 非超时异常处理过程中发生: {}", e.getMessage(), e);
        throw new RuntimeException(e);
    }
}, executorTimeOutService)
.exceptionally(e -> {
    // 最外层捕获所有异常并记录日志
    log.error("[双流程] 最外层捕获的异常: {}", e.getMessage(), e);
    
    if (req.isNeedLogger() && Objects.nonNull(req.getRiskFilterLogger())) {
        String message = (e instanceof BusinessException) ? 
                         Objects.nonNull(e.getCause()) ? e.getCause().getMessage() : e.getMessage() : 
                         e.getMessage();
                         
        RiskFilterLog riskFilterLog = new RiskFilterLog();
        riskFilterLog.setFilterType(RiskFilterTypeEnum.WITHDRAW_RISK.getCode());
        riskFilterLog.setStatus(RiskFilterStatusEnum.INITIAL.getCode());
        riskFilterLog.setSource(RiskFilterSourceEnum.WITHDRAW_RISK.getCode());
        riskFilterLog.setRequestId(req.getRequestId());
        riskFilterLog.setRiskRuleAction(RuleEnum.TRANSFERRED_TO_MANUAL_REVIEW.getRuleAction());
        riskFilterLog.setErrorMsg(StringUtils.substring(message, 0, 255));
        req.getRiskFilterLogger().accept(true, true, req.getRequestId(), riskFilterLog);
    }
    return false;
});
```

### 解释：

- **`exceptionallyAsync` 中抛出非 `TimeoutException` 的异常**：当不是超时异常时，直接将该异常重新抛出，让它继续传播。
  
- **最外层 `exceptionally` 捕获所有异常并处理日志**：最外层的 `exceptionally` 会捕获整个流程中未被处理的任何异常，并确保记录日志。这可以包括来自任务本身的异常、超时处理中的异常等。

通过这样的处理，你能够确保所有异常都能正确地被捕获和记录日志，不会有被遗漏的情况。

# 7. 那我觉得completableFuture这个东西太强大了，它处理了任务的一致性和异常问题，它几乎可以组合任何复杂的异步编排模式，而几乎不需要我们手动处理任何一致性和异常的控制问题，它都能替我们保证。为什么在实际的工作当中看到是使用它的代码很少，大多数都是通过future去实现。我认为它几乎可以替代java中的任何异步框架和工具。
你的观察非常正确，**CompletableFuture** 的确是 Java 8 中引入的非常强大的异步编程工具，它提供了灵活的任务组合和异常处理机制，可以轻松地实现复杂的异步编排。然而，虽然它具有强大的功能和潜力，但它在实际项目中的使用率相对较低，原因可以归结为以下几点：

### 1. **学习曲线**
   虽然 **CompletableFuture** 功能强大，但它相对复杂。它提供了很多组合异步任务的方法，如 `thenApply`、`thenCompose`、`handle`、`exceptionally`、`orTimeout` 等，对一些开发者而言，理解这些方法的行为、如何组合它们以及如何正确处理异常，可能需要较长时间的学习和实践。而 `Future` 则更简单，许多人已经习惯了使用传统的 `Future` 来进行异步操作。

### 2. **遗留系统和代码习惯**
   在许多企业项目中，系统可能是基于较早版本的 Java 开发的。在 Java 8 之前，开发者主要使用 `Future`、`ExecutorService` 或者第三方框架（如 Guava 的 `ListenableFuture`）来实现异步任务。即使在引入 **CompletableFuture** 之后，许多团队的代码基于已有的实现，考虑到成本和风险，短期内可能没有立即切换到新的工具。

### 3. **异步编程的复杂性**
   异步编程本身具有一定的复杂性，特别是在实际业务中涉及到共享资源、一致性、并发问题时。对于许多应用场景，开发者可能更倾向于使用同步的方式来简化代码逻辑，避免异步编程带来的复杂性。

### 4. **第三方异步框架的影响**
   在 Java 8 引入 **CompletableFuture** 之前，已经有很多第三方异步框架被广泛使用。例如：
   - **Guava 的 ListenableFuture**
   - **RxJava** 或 **Project Reactor** 提供的响应式编程模式
   - **Akka** 提供的 Actor 模型
   - **Vert.x** 等其他事件驱动框架

   这些库已经得到了广泛应用，并在某些场景下提供了更高级的功能（例如流处理、消息传递等），因此 **CompletableFuture** 可能没有成为项目的首选工具。

### 5. **传统线程模型的依赖**
   很多企业项目的架构和设计依赖于传统的线程模型，这意味着他们的任务调度和管理通常基于较早期的 `ExecutorService` 和 `Future`。特别是在分布式环境中，异步任务的调度往往会通过消息队列、事件驱动系统等来完成，开发者更愿意使用这些经过验证的架构模式，而不是使用原生的 Java 异步工具。

### 6. **微服务架构的影响**
   随着微服务架构的普及，很多异步操作交给了服务间的通信机制，例如通过 **Kafka**、**RabbitMQ** 这样的消息队列系统来实现异步消息传递。服务之间的异步调用已经通过这些工具完成，而在微服务内部，由于业务流程简单，开发者可能选择使用同步编程。

### 7. **可读性和可维护性**
   虽然 **CompletableFuture** 能够优雅地处理复杂的异步操作，但在某些场景下，它可能会使代码看起来过于复杂。如果有很多异步链式调用，代码的可读性和可维护性可能会降低，尤其对于团队中的其他成员而言，理解和维护这样的代码可能需要额外的精力。

### 8. **应用场景**
   **CompletableFuture** 的强大之处在于处理并发和复杂的异步逻辑，但并不是所有业务逻辑都需要复杂的异步处理。在很多简单的场景下，使用同步方式已经足够高效，开发者也不需要为异步编排付出额外的代码复杂性。

### 结论
**CompletableFuture** 是一个非常强大的工具，尤其在需要处理复杂的异步任务链、组合任务、异常处理和超时等场景时，它能够显著简化代码，提供优雅的解决方案。但它的强大功能也伴随着学习曲线、复杂性和可维护性的问题，这些使得它在实际工作中并不是所有场景的首选工具。

未来，随着 Java 8 及之后版本的普及，以及开发者对现代 Java 异步工具的深入理解，**CompletableFuture** 的使用率可能会逐步提升。同时，在需要处理复杂异步逻辑的场景下，**CompletableFuture** 确实是一个非常值得考虑的解决方案，它能够在很多方面替代传统的异步框架和工具。
